openapi: 3.0.0
info:
  title: Simple Calculation API
  description: This is a simple calculation API
  contact:
    email: almoghr36@gmail.com
  version: 1.0.0
servers:
- url: http://127.0.0.1:8000
security:
- jwtAuth: []
paths:
  /login:
    post:
      description: enter username and password to gain the auth token
      operationId: loginPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login_body'
        required: true
      responses:
        "200":
          description: logged in successfully
          headers:
            Set-Cookie:
              description: Authentication cookie
              style: simple
              explode: false
              schema:
                $ref: '#/components/schemas/AuthAccessToken'
              examples:
                example1:
                  value: loginValidationCookie=example; Path=/; HttpOnly
        "400":
          description: wrong username or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestSchema'
      security: []
      x-swagger-router-controller: Default
  /calculate:
    post:
      description: Receives two numbers and performs a mathematical calculation on
        them
      operationId: calculatePOST
      parameters:
      - name: X-Calculation-Method
        in: header
        description: Specifies the method of calculation to be used
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/calculate_body'
        required: true
      responses:
        "200":
          description: Successfully calculated the numbers you've provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestSchema'
        "401":
          description: Unauthorized
      security:
      - jwtAuth: []
      x-swagger-router-controller: Default
components:
  schemas:
    InvalidRequestSchema:
      type: object
      properties:
        message:
          type: string
    AuthAccessToken:
      type: object
      properties:
        id:
          type: integer
          format: int64
    login_body:
      required:
      - password
      - username
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    calculate_body:
      required:
      - first_num
      - second_num
      type: object
      properties:
        first_num:
          type: integer
        second_num:
          type: integer
    inline_response_200:
      type: object
      properties:
        calculated_number:
          type: integer
      example:
        calculated_number: 0
  securitySchemes:
    jwtAuth:
      type: apiKey
      description: HTTP-only cookie containing the JWT token
      name: authorization
      in: cookie
